name: shopping_store
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.1
  get: ^4.7.2
  get_storage: ^2.1.1
  url_launcher: ^6.3.2
  iconsax: ^0.0.8
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  readmore: ^3.0.0
  logger: ^2.6.0
  iconsax: ^0.0.8

  # Firebase Packages
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  google_sign_in: ^7.1.0

upertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS --------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/animations/
    # - assets/images/banners/
    - assets/images/content/
    - assets/images/on_boarding_images/
    # - assets/images/products/
    - assets/images/reviews/

  #--------------- LOCAL FONTS --------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
