// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMN-2AhZvHL2DAKf2M1OZHIpjlXsXuCIg',
    appId: '1:872998617865:web:106715cb70a42d0c75c9d8',
    messagingSenderId: '872998617865',
    projectId: 'extreme-zephyr-395310',
    authDomain: 'extreme-zephyr-395310.firebaseapp.com',
    storageBucket: 'extreme-zephyr-395310.firebasestorage.app',
    measurementId: 'G-G4L4K5D781',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwNColMLx4lxL2mm1gXF-fexoyhmgEOV4',
    appId: '1:872998617865:android:c71199c37b33fdab75c9d8',
    messagingSenderId: '872998617865',
    projectId: 'extreme-zephyr-395310',
    storageBucket: 'extreme-zephyr-395310.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc5DDObcEAprO5PfI9rk43l5WVp-eGpro',
    appId: '1:872998617865:ios:309d3f01a2242bdf75c9d8',
    messagingSenderId: '872998617865',
    projectId: 'extreme-zephyr-395310',
    storageBucket: 'extreme-zephyr-395310.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc5DDObcEAprO5PfI9rk43l5WVp-eGpro',
    appId: '1:872998617865:ios:309d3f01a2242bdf75c9d8',
    messagingSenderId: '872998617865',
    projectId: 'extreme-zephyr-395310',
    storageBucket: 'extreme-zephyr-395310.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvyLyXuwfl9XwRP94XWWGKbgoSV8bCYZQ',
    appId: '1:872998617865:web:38b8d52be10d80c975c9d8',
    messagingSenderId: '872998617865',
    projectId: 'extreme-zephyr-395310',
    authDomain: 'extreme-zephyr-395310.firebaseapp.com',
    storageBucket: 'extreme-zephyr-395310.firebasestorage.app',
    measurementId: 'G-19SZLRDNJD',
  );
}
